# Automatically generated by configure - do not modify
SRC_PATH=/Users/sparksammy/Downloads/20C69/xnu-qemu-arm64-5.1.0/roms/seabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
